version: '3.7'

services:
  app:
    image: techno/azusa:0.1.0
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ./azusa
    user: "1000:1000"
    environment:
      VOLUME: /data
    volumes:
      - "./data:/data"
      - "./config:/app/config"
      - "./log:/app/log"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
