version: '3.7'

services:
  app:
    image: techno/azusa:0.1.0
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ./static-rocket
    ports:
      - "8000:8000"
    volumes:
      - "./data:/data"
    tty: true
    stdin_open: true
